created_date: 10/27/2023 13:16:22
dataset:
  class_names:
  - plastic
  - metal
  - paper
  - glass
  testset: Aquatrash
  trainset: augmented_trashnet
desc: "The model detects trash: plastic, metal, paper, and glass\t"
miscs:
  ckpt_interval_epochs: 100
  eval_interval_epochs: 1
model:
  ZeroHead:
    act: silu
    nms_conf_thre: 0.5
    nms_iou_thre: 0.7
    reg_max: 16
model_name: trash_detection
train:
  augment:
    mosaic_mixup:
      degrees: 10.0
      mixup_prob: 0.15
      mosaic_scale:
      - 0.1
      - 2.0
      shear: 2.0
      translate: 0.2
    transform:
      image_max_range:
      - 640
      - 640
  base_lr_per_img: 0.00015625
  batch_size: 16
  min_lr_ratio: 0.05
  momentum: 0.9
  no_aug_epochs: 16
  total_epochs: 3000
  warmup_epochs: 5
  weight_decay: 0.0005
